### ISSUE TITLE
Sections overlapping

### ISSUE THREAD

**Issue by personalyisus** [jaresdev/jaresdev-portfolio#15]
Hi :) 

Viewed your portfolio page but it seems there may be a css issue somewhere, the cards/sections are not displayed properly and some content is not visible, just wanted to let you know!
![image](https://github.com/user-attachments/assets/123b7dc9-9e13-41a6-80a6-f7bb35ea0a82)

This was a firefox screenshot

**Comment by jaresdev** [comment]
Hi! Thank you for your comment. Could you please let me know your screen resolution? It seems to be something about that

**Comment by personalyisus** [comment]
The screen where I was seeing this has a 1920x1080 resolution; other size breakpoints were working fine, it was only on bigger sizes that this happened

However I see you already fixed it in #16  , nice :) 👍 

![image](https://github.com/user-attachments/assets/eb8f94ef-6e4e-4c37-80b4-89ba81f5fc9f)
